- lib/sitemap.xml
Either we should do this (for clarity), or change everything else to `post` (for easier copy-pasting between sections).
> Call pages "pages" in sitemap.xml

- lib/sitemap.xml
- spec/jekyll-sitemap_spec.rb
I'm sure this conflicts with #33
Once one is merged, I can rebase the other.
> Remove `changefreq`

- lib/sitemap.xml
- spec/jekyll-sitemap_spec.rb
Removes the default priority for all items as per [Google's recommendations](https://github.com/jekyll/jekyll-sitemap/pull/21#issuecomment-50813988)
#21
> Remove default Priority

- lib/sitemap.xml
- spec/fixtures/some-subfolder/test_index.html
- spec/jekyll-sitemap_spec.rb
Fixes #67 
I wish that Liquid provided a `replace_last` filter analogous to [`replace_first`](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L160-L163).
This could break things if there is a directory named `/index.html/` or a file who's name begins with `/index.html`
> Don't strip 'index.html' when there is more to filename

- jekyll-sitemap.gemspec
- lib/jekyll-sitemap.rb
- lib/sitemap.xml
- script/cibuild
- spec/fixtures/_config.yml
- spec/fixtures/_posts/2015-01-18-jekyll-last-modified-at.md
- spec/fixtures/jekyll-last-modified-at/page.html
- spec/test_jekyll-last-modified-at.rb
`<lastmod>` [is an optional tag](http://www.sitemaps.org/protocol.html#lastmoddef).
Including it as we currently do has the advantage of letting search engines know if nothing on the site has changed for quite a while (as in, the site has not been regenerated), but the disadvantage of telling search engines that every page on the site has changed each time the site is regenerated, even if no pages have been updated.
I'm not really sure which is worse&hellip;
> Do not assume all pages have changed

- lib/jekyll-sitemap.rb
- spec/jekyll-sitemap_spec.rb
I noticed jekyll-sitemap generates some warnings on Travis build: https://travis-ci.org/yous/yous.github.io/builds/52976809
- `/\s/` is equivalent to `/[ \t\r\n\f]/`. See http://ruby-doc.org/core-2.2.0/doc/regexp_rdoc.html#label-Character+Classes.
> Remove duplicated range from regex

- .travis.yml
- Gemfile
- lib/sitemap.xml
- script/cibuild
Hope I crossed all the Ts and dotted all Is.
jekyll/jekyll#3945
> Test against Jekyll 3

- lib/sitemap.xml
- spec/fixtures/_my_collection/this-has-non-standard-chars.md
- spec/jekyll-sitemap_spec.rb
* All sitemap URLs are required to be URI-encoded
* Adding built-in Jekyll template `uri_escape` handles this
* Test shows successful handling of non-alphanumeric and non-ASCII characters
> URI encode sitemap URLs

- script/bootstrap
- script/cibuild
These simple scripts do not use any bash features, so do not
require needless extra dependency
> Fix shebangs from /bin/bash to /bin/sh

- lib/sitemap.xml
- spec/jekyll-sitemap_spec.rb
Here is a first attempt at fixing #91 in a way that is backward compatible with Jekyll 2.
> Do not include 'posts' collection twice

- .travis.yml
- Gemfile
I split the GitHub pages stuff into its own gemfile to avoid environment variable trickery.
It seems that for some reason bundler chokes when loading this project's gem with the **pages-gem**. It obviously wasn't this way before, I am unsure of what changed.
It seems I can get around that by loading our test version of **jekyll-sitemap** by path rather than through `gemspec`, but I have no idea what the implications of that are. We would need to add all the dev deps by hand; seems like a nasty terrible hack.
I will admit that I'm in a bit over my head here. Any suggestions would be greatly appreciated.
> Fix GitHub Pages tests

- lib/jekyll-sitemap.rb
- spec/fixtures/some-subfolder/htm.htm
- spec/fixtures/some-subfolder/xhtml.xhtml
- spec/jekyll-sitemap_spec.rb
This mirrors [Jekyll's current behavior](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/page.rb#L19-L26) as of Jekyll/Jekyll#4160
> Allow HTML files to end with .xhtml or .htm

- lib/jekyll-sitemap.rb
> Smell - Semantics - Invalid Hash Initialization - Use `{}` instead of `Hash` to initialize a hash.
> Use {} instead of Hash.new

- lib/jekyll-sitemap.rb
Credit to @benbalter for [this idea](https://github.com/benbalter/jekyll-seo-tag/commit/1ad8107a4e9ce65d54d23251e223110fadb18e35).
> Simplify whitespace regex

- lib/jekyll/jekyll-sitemap.rb
Setting @site.config["time"] causes problems when Jekyll is operating in --draft mode. See: https://github.com/jekyll/jekyll-sitemap/issues/130 and https://github.com/jekyll/jekyll-feed/issues/135
> Don't set @site.config["time"] on sitemap generation

- jekyll-sitemap.gemspec
Now that Jekyll core is building absolute URLs for us, we're not using Addressable any more.
> Drop Addressable dependency

- README.md
I've renamed the issues section to "Known Issues". Also, I've moved the section before contributing, as it should grab more attention of casual users than contributing section — it's basically about forking.
I've also thought about adding an intro paragraph for Known Issues, but I am not so sure about that. If you want to have it, I'll add it.
> Fix #134: Rename "Issues" to "Known Issues"

- .rubocop.yml
- README.md
- lib/jekyll/jekyll-sitemap.rb
This PR takes advantage of some of the newer features in Jekyll to reduce some of the code necessary. Now that we require Jekyll 3.3, we do not need to keep all the old workarounds.
> Refactor and add sitemap to `site.pages`

- README.md
I've made some tests and completed the documentation concerning the `<lasmod>` tag, as @pathawks is working on other priorities 😄 (#104)
> Fix #104: Add explanation in README for <lastmod> tag

- lib/jekyll/jekyll-sitemap.rb
- lib/robots.txt
- spec/jekyll-sitemap_spec.rb
Fixes https://github.com/jekyll/jekyll-sitemap/issues/114.
> Add robots.txt when none exists

- .travis.yml
This will ensure that tests get the proper date when testing with **jekyll-last-modified-at**
> Travis should do a deep clone

- lib/sitemap.xml
This monster of a PR attempts to reduce code reuse in the sitemap template.
- Drop support for Jekyll 2.x style collections (since we now require Jekyll 3.3+)
- Allow Posts to be output with other collections (since Posts are a collection in Jekyll 3+)
- Use new `where_exp` filter instead of `unless`
Ideally, I would love to only have the `<url>` template _once_ (instead of current three times). If `page.static_files`, `site.html_pages`, and `collection.docs` were arrays, I could use the Liquid `concat` filter to string them all together and iterate over everything in one for loop. I am not sure this is currently possible.
> DRY in sitemap.xml

- .travis.yml
Ok, so Travis didn't auto-deploy the new :gem: as I had hoped.
After doing some digging, it seems Travis wasn't auto-deploying tags because it wasn't building tags at all.  Travis sees tags as branches, so by telling Travis to only build the master branch, Travis will never build tags.
```yaml
branches:
only:
- master
```
The last time [Travis built a tag was v0.9.0](https://travis-ci.org/jekyll/jekyll-sitemap/branches) which [did not include the `branches: only: - master` directive](https://github.com/jekyll/jekyll-sitemap/blob/v0.9.0/.travis.yml). Once [this was added in v0.10.0](https://github.com/jekyll/jekyll-sitemap/blob/v0.10.0/.travis.yml#L18-L20), Travis stopped building tags.
Travis sees tags as branches, so by allowing _branches_ that look like a tag, Travis should build our …
> Allow Travis to build tags

- lib/sitemap.xml
- spec/fixtures/_config.yml
- spec/jekyll-sitemap_spec.rb
The `sitemap.xml` doesn't obey the `sitemap` front matter variable when looping over the static files (in the same way it does for collections and pages). This means excluded static files still get included in the generated sitemap.
This PR just checks that `sitemap != false` for static files, and adds in the necessary tests.
> Remove excluded static files from the sitemap

- .travis.yml
- jekyll-sitemap.gemspec
- spec/jekyll-sitemap_spec.rb
This PR bumps the Jekyll gem dependency to [v3.4.2](https://github.com/jekyll/jekyll/releases/tag/v3.4.2) (the release containing front matter defaults for static files).
It also bumps the version used by the GitHub Pages test environment to [v3.4.3](https://github.com/jekyll/jekyll/releases/tag/v3.4.3) (the latest supported).
> Condition the static file tests on Jekyll 3.4.2 and above

- lib/sitemap.xml
- spec/fixtures/some-subfolder/index.html
- spec/jekyll-sitemap_spec.rb
the default path for a subfolder index file is the permalink version:
`/directory/index.html` renders sitemap path as `/directory/`
felt the same should happen for static html files that are included.
> filter/replace static index.html paths to permalink

- .travis.yml
This should make Travis only try to deploy a Gem once, and avoid the race condition encountered during the v1.1.0 release
This is a bit of a hack. To make sure that only one build tries to deploy, I am setting a special flag during the GHP build, and then only trying to deploy if that flag is set. This will prevent deploy during any other Travis build.
Fixes #165
> Fix Travis Deploy

- README.md
Note that for sites using Github Pages gem, this plugin must be included in _config.yml.
> Add note about use with Github Pages gem

- README.md
> Docs: set site.url in config

- README.md
> Docs: Build for production

- lib/jekyll/jekyll-sitemap.rb
- spec/fixtures/_config.yml
- spec/jekyll-sitemap_spec.rb
Looking into https://github.com/jekyll/jekyll-sitemap/issues/200, I realized that we test a binary file, but not a static text file, which may behave differently, per https://github.com/jekyll/jekyll-sitemap/issues/180.
> Test that HTML files are excluded

- .rubocop.yml
- .travis.yml
- Gemfile
- jekyll-sitemap.gemspec
- Re-introduce Ruby 2.3 support for backwards compatibiility
- Allow testing with Jekyll 4.0 pre-release versions
> Update plugin metadata and dev environment

- jekyll-sitemap.gemspec
- spec/test_jekyll-last-modified-at.rb
Simulate plugin behavior so that changes to plugin's output do not affect this project's tests
> Simulate `last_modified_at` injection by plugin

- lib/jekyll/jekyll-sitemap.rb
- spec/jekyll-sitemap_spec.rb
One potential use case for this would be to add XML feeds to your
sitemap. This is handy so that crawlers such as Google can better find
your feeds.
This closes #252.
> Add XML file type to INCLUDED_EXTENSIONS
